<div class="site-wrap">


<div class="site-blocks-cover overlay" style="background-image: url(img/hero_1.jpg);" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row align-items-center justify-content-center text-center">

            <div class="col-md-12" data-aos="fade-up" data-aos-delay="400">

                <div class="row justify-content-center mb-4">
                    <div class="col-md-8 text-center">
                        <h1>Somos expertos <span class="typed-words"></span></h1>
                        <p class="lead mb-5">Consultoria em Programas de Integridade e Compliance</p>
                        <div><a href="#" class="btn btn-primary btn-md">Conoce Más</a></div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<section class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-4">
                <div class="p-3 box-with-humber">
                    <div class="number-behind">01.</div>
                    <h2>Visión</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et praesentium eos nulla qui commodi consectetur beatae fugiat. Veniam iste rerum perferendis.</p>
                </div>
            </div>

            <div class="col-md-6 col-lg-4">
                <div class="p-3 box-with-humber">
                    <div class="number-behind">02.</div>
                    <h2>Misión</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et praesentium eos nulla qui commodi consectetur beatae fugiat. Veniam iste rerum perferendis.</p>
                </div>
            </div>

            <div class="col-md-6 col-lg-4">
                <div class="p-3 box-with-humber">
                    <div class="number-behind">03.</div>
                    <h2>Valores</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et praesentium eos nulla qui commodi consectetur beatae fugiat. Veniam iste rerum perferendis.</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="site-section">
    <div class="container">
        <div class="row mb-5 justify-content-center">
            <div class="col-md-8 text-center">
                <h2 class="text-black h1 site-section-heading text-center">Proyectos</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores, itaque neque, delectus odio iure explicabo.</p>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-lg-4">
                <a href="#" class="media-1">
                    <img src="img/img_1.jpg" alt="Image" class="img-fluid">
                    <div class="media-1-content">
                        <h2>Project Name 1</h2>
                        <span class="category">Web Application</span>
                    </div>
                </a>
            </div>
            <div class="col-md-6 col-lg-4">
                <a href="#" class="media-1">
                    <img src="img/img_2.jpg" alt="Image" class="img-fluid">
                    <div class="media-1-content">
                        <h2>Project Name 2</h2>
                        <span class="category">Branding</span>
                    </div>
                </a>
            </div>
            <div class="col-md-6 col-lg-4">
                <a href="#" class="media-1">
                    <img src="img/img_3.jpg" alt="Image" class="img-fluid">
                    <div class="media-1-content">
                        <h2>Project Name 3</h2>
                        <span class="category">Website</span>
                    </div>
                </a>
            </div>

            <div class="col-12 text-center mt-5">
                <a href="work.html" class="btn btn-primary btn-md">Show All Works</a>
            </div>


        </div>
    </div>
</section>


<section class="site-section testimonial-wrap">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <h2 class="text-black h1 site-section-heading text-center">Testimonials</h2>
            </div>
        </div>
    </div>
    <div class="slide-one-item home-slider owl-carousel">
        <div>
            <div class="testimonial">

                <blockquote class="mb-5">
                    <p>&ldquo;Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur unde reprehenderit aperiam quaerat fugiat repudiandae explicabo animi minima fuga beatae illum eligendi incidunt consequatur. Amet dolores excepturi earum unde iusto.&rdquo;</p>
                </blockquote>

                <figure class="mb-4 d-flex align-items-center justify-content-center">
                    <div><img src="img/person_3.jpg" alt="Image" class="w-50 img-fluid mb-3"></div>
                    <p>John Smith</p>
                </figure>
            </div>
        </div>
        <div>
            <div class="testimonial">

                <blockquote class="mb-5">
                    <p>&ldquo;Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur unde reprehenderit aperiam quaerat fugiat repudiandae explicabo animi minima fuga beatae illum eligendi incidunt consequatur. Amet dolores excepturi earum unde iusto.&rdquo;</p>
                </blockquote>
                <figure class="mb-4 d-flex align-items-center justify-content-center">
                    <div><img src="img/person_2.jpg" alt="Image" class="w-50 img-fluid mb-3"></div>
                    <p>Christine Aguilar</p>
                </figure>

            </div>
        </div>

        <div>
            <div class="testimonial">

                <blockquote class="mb-5">
                    <p>&ldquo;Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur unde reprehenderit aperiam quaerat fugiat repudiandae explicabo animi minima fuga beatae illum eligendi incidunt consequatur. Amet dolores excepturi earum unde iusto.&rdquo;</p>
                </blockquote>
                <figure class="mb-4 d-flex align-items-center justify-content-center">
                    <div><img src="img/person_4.jpg" alt="Image" class="w-50 img-fluid mb-3"></div>
                    <p>Robert Spears</p>
                </figure>


            </div>
        </div>

        <div>
            <div class="testimonial">

                <blockquote class="mb-5">
                    <p>&ldquo;Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur unde reprehenderit aperiam quaerat fugiat repudiandae explicabo animi minima fuga beatae illum eligendi incidunt consequatur. Amet dolores excepturi earum unde iusto.&rdquo;</p>
                </blockquote>
                <figure class="mb-4 d-flex align-items-center justify-content-center">
                    <div><img src="img/person_5.jpg" alt="Image" class="w-50 img-fluid mb-3"></div>
                    <p>Bruce Rogers</p>
                </figure>

            </div>
        </div>

    </div>
</section>

<section class="site-section bg-light">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <h2 class="text-black h1 site-section-heading text-center">Blog</h2>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
                <div class="h-entry">
                    <img src="img/img_1.jpg" alt="Image" class="img-fluid">
                    <h2 class="font-size-regular"><a href="#">Create Beautiful Website In Less Than An Hour</a></h2>
                    <div class="meta mb-4">Ham Brook <span class="mx-2">&bullet;</span> Jan 18, 2019<span class="mx-2">&bullet;</span> <a href="#">News</a></div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus eligendi nobis ea maiores sapiente veritatis reprehenderit suscipit quaerat rerum voluptatibus a eius.</p>
                    <p><a href="#">Continue Reading...</a></p>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
                <div class="h-entry">
                    <img src="img/img_2.jpg" alt="Image" class="img-fluid">
                    <h2 class="font-size-regular"><a href="#">Create Beautiful Website In Less Than An Hour</a></h2>
                    <div class="meta mb-4">James Phelps <span class="mx-2">&bullet;</span> Jan 18, 2019<span class="mx-2">&bullet;</span> <a href="#">News</a></div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus eligendi nobis ea maiores sapiente veritatis reprehenderit suscipit quaerat rerum voluptatibus a eius.</p>
                    <p><a href="#">Continue Reading...</a></p>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
                <div class="h-entry">
                    <img src="img/img_1.jpg" alt="Image" class="img-fluid">
                    <h2 class="font-size-regular"><a href="#">Create Beautiful Website In Less Than An Hour</a></h2>
                    <div class="meta mb-4">James Phelps <span class="mx-2">&bullet;</span> Jan 18, 2019<span class="mx-2">&bullet;</span> <a href="#">News</a></div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus eligendi nobis ea maiores sapiente veritatis reprehenderit suscipit quaerat rerum voluptatibus a eius.</p>
                    <p><a href="#">Continue Reading...</a></p>
                </div>
            </div>

        </div>
    </div>
</section>
<!--
<a href="#" class="bg-primary py-5 d-block">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md10"><h2 class="text-white">Hire Us &amp; Let's Get Started</h2></div>
        </div>
    </div>
</a>
    -->

</div>
